CUDA_VISIBLE_DEVICES=0 torchrun --nnodes=1 --nproc_per_node 1 --master_port 29514 \
    -m opensora.sample.sample \
    --model_path "/home/r/Documents/Open-Sora-Plan/open_sora_plan_v1_3_0/any93x640x640" \
    --version "v1_3" \
    --num_frames 93 \
    --height 352 \
    --width 640 \
    --cache_dir "./cache_dir" \
    --text_encoder_name_1 "/home/r/Documents/Open-Sora-Plan/mt5-xxl-pytorch/models--google--mt5-xxl/snapshots/e07c395916dfbc315d4e5e48b4a54a1e8821b5c0" \
    --text_prompt "examples/sora.txt" \
    --ae "WFVAEModel_D8_4x8x8" \
    --ae_path "/home/r/Documents/Open-Sora-Plan/open_sora_plan_v1_3_0/vae" \
    --save_img_path "./train_1_3_nomotion_fps18" \
    --fps 18 \
    --guidance_scale 7.5 \
    --num_sampling_steps 100 \
    --max_sequence_length 512 \
    --sample_method "EulerAncestralDiscrete" \
    --seed 1234 \
    --num_samples_per_prompt 1 \
    --rescale_betas_zero_snr \
    --prediction_type "v_prediction" \
    --save_memory \
    --device "cuda"
